# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_char_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_char(object):
    def setupUi(self, add_char):
        add_char.setObjectName("add_char")
        add_char.resize(797, 337)
        add_char.setMinimumSize(QtCore.QSize(717, 337))
        add_char.setMaximumSize(QtCore.QSize(900, 551))
        add_char.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(add_char)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(add_char)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(add_char)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(add_char)
        self.label.setMinimumSize(QtCore.QSize(429, 16))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.client_id_input = QtWidgets.QLineEdit(add_char)
        self.client_id_input.setEnabled(True)
        self.client_id_input.setObjectName("client_id_input")
        self.verticalLayout.addWidget(self.client_id_input)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(add_char)
        self.label_2.setMinimumSize(QtCore.QSize(429, 16))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.secret_key_input = QtWidgets.QLineEdit(add_char)
        self.secret_key_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.secret_key_input.setObjectName("secret_key_input")
        self.verticalLayout_2.addWidget(self.secret_key_input)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(add_char)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.save_dev = QtWidgets.QPushButton(add_char)
        self.save_dev.setMinimumSize(QtCore.QSize(0, 31))
        self.save_dev.setStyleSheet("")
        self.save_dev.setObjectName("save_dev")
        self.verticalLayout_3.addWidget(self.save_dev)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.frame = QtWidgets.QFrame(add_char)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.load_sso = QtWidgets.QVBoxLayout()
        self.load_sso.setSpacing(0)
        self.load_sso.setObjectName("load_sso")
        self.verticalLayout_4.addLayout(self.load_sso)
        self.horizontalLayout.addWidget(self.frame)
        self.label.setBuddy(self.client_id_input)
        self.label_2.setBuddy(self.secret_key_input)

        self.retranslateUi(add_char)
        QtCore.QMetaObject.connectSlotsByName(add_char)

    def retranslateUi(self, add_char):
        _translate = QtCore.QCoreApplication.translate
        add_char.setWindowTitle(_translate("add_char", "Add Characters"))
        self.label_3.setText(_translate("add_char",
                                        "Your developer application key can be created at: https://developers.eveonline.com/applications/create "))
        self.label.setText(_translate("add_char", "Client ID:"))
        self.label_2.setText(_translate("add_char", "Secret Key:"))
        self.save_dev.setText(_translate("add_char", "Save"))
