# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_pane_char_view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pane_char_view(object):
    def setupUi(self, pane_char_view):
        pane_char_view.setObjectName("pane_char_view")
        pane_char_view.resize(853, 523)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(pane_char_view)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(pane_char_view)
        self.frame_3.setMinimumSize(QtCore.QSize(835, 357))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 357))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(664, 337))
        self.frame.setMaximumSize(QtCore.QSize(682, 337))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pilot_image = QtWidgets.QLabel(self.frame)
        self.pilot_image.setMinimumSize(QtCore.QSize(128, 128))
        self.pilot_image.setMaximumSize(QtCore.QSize(128, 128))
        self.pilot_image.setText("")
        self.pilot_image.setPixmap(QtGui.QPixmap("media/static/icons/blank_char.jpg"))
        self.pilot_image.setScaledContents(True)
        self.pilot_image.setObjectName("pilot_image")
        self.verticalLayout.addWidget(self.pilot_image)
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.text_account_status = QtWidgets.QLabel(self.frame)
        self.text_account_status.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_account_status.setFont(font)
        self.text_account_status.setStyleSheet("color: rgb(207, 12, 15);")
        self.text_account_status.setObjectName("text_account_status")
        self.verticalLayout.addWidget(self.text_account_status)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.text_active_until = QtWidgets.QLabel(self.frame)
        self.text_active_until.setEnabled(True)
        self.text_active_until.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_active_until.setFont(font)
        self.text_active_until.setStyleSheet("color: rgb(207, 12, 15);")
        self.text_active_until.setObjectName("text_active_until")
        self.verticalLayout.addWidget(self.text_active_until)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.text_pilot_name = QtWidgets.QLabel(self.frame)
        self.text_pilot_name.setMinimumSize(QtCore.QSize(210, 15))
        self.text_pilot_name.setMaximumSize(QtCore.QSize(437, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_pilot_name.setFont(font)
        self.text_pilot_name.setObjectName("text_pilot_name")
        self.gridLayout.addWidget(self.text_pilot_name, 0, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.pilot_faction = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pilot_faction.setFont(font)
        self.pilot_faction.setObjectName("pilot_faction")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.pilot_faction)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.text_isk_balance = QtWidgets.QLabel(self.frame)
        self.text_isk_balance.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_isk_balance.setFont(font)
        self.text_isk_balance.setObjectName("text_isk_balance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_isk_balance)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.text_birthday = QtWidgets.QLabel(self.frame)
        self.text_birthday.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_birthday.setFont(font)
        self.text_birthday.setObjectName("text_birthday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_birthday)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.text_corp = QtWidgets.QLabel(self.frame)
        self.text_corp.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_corp.setFont(font)
        self.text_corp.setObjectName("text_corp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_corp)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.text_alliance = QtWidgets.QLabel(self.frame)
        self.text_alliance.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_alliance.setFont(font)
        self.text_alliance.setObjectName("text_alliance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text_alliance)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.text_sec_status = QtWidgets.QLabel(self.frame)
        self.text_sec_status.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_sec_status.setFont(font)
        self.text_sec_status.setObjectName("text_sec_status")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.text_sec_status)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.text_active_ship = QtWidgets.QLabel(self.frame)
        self.text_active_ship.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_active_ship.setFont(font)
        self.text_active_ship.setObjectName("text_active_ship")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.text_active_ship)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.text_located_at = QtWidgets.QLabel(self.frame)
        self.text_located_at.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_located_at.setFont(font)
        self.text_located_at.setObjectName("text_located_at")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.text_located_at)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.text_docked_at = QtWidgets.QLabel(self.frame)
        self.text_docked_at.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_docked_at.setFont(font)
        self.text_docked_at.setObjectName("text_docked_at")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.text_docked_at)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 7, -1, -1)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.text_attributes_intel = QtWidgets.QLabel(self.frame)
        self.text_attributes_intel.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_attributes_intel.setFont(font)
        self.text_attributes_intel.setObjectName("text_attributes_intel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_attributes_intel)
        self.label_13 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.text_attributes_perception = QtWidgets.QLabel(self.frame)
        self.text_attributes_perception.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_attributes_perception.setFont(font)
        self.text_attributes_perception.setObjectName("text_attributes_perception")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_attributes_perception)
        self.label_10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.text_attributes_memory = QtWidgets.QLabel(self.frame)
        self.text_attributes_memory.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_attributes_memory.setFont(font)
        self.text_attributes_memory.setObjectName("text_attributes_memory")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_attributes_memory)
        self.label_11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.text_attributes_charisma = QtWidgets.QLabel(self.frame)
        self.text_attributes_charisma.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_attributes_charisma.setFont(font)
        self.text_attributes_charisma.setObjectName("text_attributes_charisma")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_attributes_charisma)
        self.label_12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.text_attributes_willpower = QtWidgets.QLabel(self.frame)
        self.text_attributes_willpower.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_attributes_willpower.setFont(font)
        self.text_attributes_willpower.setObjectName("text_attributes_willpower")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text_attributes_willpower)
        self.gridLayout.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 7, -1, -1)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.text_bonus_remap_count = QtWidgets.QLabel(self.frame)
        self.text_bonus_remap_count.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_bonus_remap_count.setFont(font)
        self.text_bonus_remap_count.setObjectName("text_bonus_remap_count")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_bonus_remap_count)
        self.label_15 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.text_next_remap_datetime = QtWidgets.QLabel(self.frame)
        self.text_next_remap_datetime.setMinimumSize(QtCore.QSize(247, 0))
        self.text_next_remap_datetime.setMaximumSize(QtCore.QSize(247, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_next_remap_datetime.setFont(font)
        self.text_next_remap_datetime.setObjectName("text_next_remap_datetime")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_next_remap_datetime)
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.text_next_clone_jump = QtWidgets.QLabel(self.frame)
        self.text_next_clone_jump.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_next_clone_jump.setFont(font)
        self.text_next_clone_jump.setObjectName("text_next_clone_jump")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_next_clone_jump)
        self.label_17 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.text_jump_fatigue_remaining = QtWidgets.QLabel(self.frame)
        self.text_jump_fatigue_remaining.setMinimumSize(QtCore.QSize(51, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_jump_fatigue_remaining.setFont(font)
        self.text_jump_fatigue_remaining.setObjectName("text_jump_fatigue_remaining")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_jump_fatigue_remaining)
        self.gridLayout.addLayout(self.formLayout_3, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(314, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(314, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 90)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(226, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.text_api_nextupdate_countdown = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_api_nextupdate_countdown.setFont(font)
        self.text_api_nextupdate_countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.text_api_nextupdate_countdown.setObjectName("text_api_nextupdate_countdown")
        self.verticalLayout_3.addWidget(self.text_api_nextupdate_countdown)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.text_known_skills = QtWidgets.QLabel(self.frame_2)
        self.text_known_skills.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_known_skills.setFont(font)
        self.text_known_skills.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.text_known_skills.setObjectName("text_known_skills")
        self.horizontalLayout_4.addWidget(self.text_known_skills)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.text_skills_at_level5 = QtWidgets.QLabel(self.frame_2)
        self.text_skills_at_level5.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_skills_at_level5.setFont(font)
        self.text_skills_at_level5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.text_skills_at_level5.setObjectName("text_skills_at_level5")
        self.horizontalLayout_3.addWidget(self.text_skills_at_level5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.text_total_sp = QtWidgets.QLabel(self.frame_2)
        self.text_total_sp.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_total_sp.setFont(font)
        self.text_total_sp.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.text_total_sp.setObjectName("text_total_sp")
        self.horizontalLayout_2.addWidget(self.text_total_sp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setMinimumSize(QtCore.QSize(101, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.text_freeSP = QtWidgets.QLabel(self.frame_2)
        self.text_freeSP.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_freeSP.setFont(font)
        self.text_freeSP.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.text_freeSP.setObjectName("text_freeSP")
        self.horizontalLayout_5.addWidget(self.text_freeSP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 264, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)

        self.retranslateUi(pane_char_view)
        QtCore.QMetaObject.connectSlotsByName(pane_char_view)

    def retranslateUi(self, pane_char_view):
        _translate = QtCore.QCoreApplication.translate
        pane_char_view.setWindowTitle(_translate("pane_char_view", "Form"))
        self.label_18.setText(_translate("pane_char_view", "Account Status:"))
        self.text_account_status.setText(_translate("pane_char_view", "Unknown"))
        self.label_19.setText(_translate("pane_char_view", "Active Until:"))
        self.text_active_until.setText(_translate("pane_char_view", "Unknown"))
        self.text_pilot_name.setText(_translate("pane_char_view", "pilot_name"))
        self.pilot_faction.setText(_translate("pane_char_view", "Unknown"))
        self.label.setText(_translate("pane_char_view", "Balance:"))
        self.text_isk_balance.setText(_translate("pane_char_view", "Unknown"))
        self.label_2.setText(_translate("pane_char_view", "Birthday:"))
        self.text_birthday.setText(_translate("pane_char_view", "Unknown"))
        self.label_3.setText(_translate("pane_char_view", "Corporation:"))
        self.text_corp.setText(_translate("pane_char_view", "Unknown"))
        self.label_4.setText(_translate("pane_char_view", "Alliance:"))
        self.text_alliance.setText(_translate("pane_char_view", "Unknown"))
        self.label_5.setText(_translate("pane_char_view", "Security Status:"))
        self.text_sec_status.setText(_translate("pane_char_view", "Unknown"))
        self.label_6.setText(_translate("pane_char_view", "Active Ship:"))
        self.text_active_ship.setText(_translate("pane_char_view", "Unknown"))
        self.label_7.setText(_translate("pane_char_view", "Located In:"))
        self.text_located_at.setText(_translate("pane_char_view", "Unknown"))
        self.label_8.setText(_translate("pane_char_view", "Docked At:"))
        self.text_docked_at.setText(_translate("pane_char_view", "Unknown"))
        self.label_9.setText(_translate("pane_char_view", "Intelligence:"))
        self.text_attributes_intel.setText(_translate("pane_char_view", "Unknown"))
        self.label_13.setText(_translate("pane_char_view", "Perception:"))
        self.text_attributes_perception.setText(_translate("pane_char_view", "Unknown"))
        self.label_10.setText(_translate("pane_char_view", "Memory:"))
        self.text_attributes_memory.setText(_translate("pane_char_view", "Unknown"))
        self.label_11.setText(_translate("pane_char_view", "Charisma:"))
        self.text_attributes_charisma.setText(_translate("pane_char_view", "Unknown"))
        self.label_12.setText(_translate("pane_char_view", "Willpower:"))
        self.text_attributes_willpower.setText(_translate("pane_char_view", "Unknown"))
        self.label_14.setText(_translate("pane_char_view", "Bonus Remaps:"))
        self.text_bonus_remap_count.setText(_translate("pane_char_view", "Unknown"))
        self.label_15.setText(_translate("pane_char_view", "Next Neural Remap:"))
        self.text_next_remap_datetime.setText(_translate("pane_char_view", "Unknown"))
        self.label_16.setText(_translate("pane_char_view", "Next Clone Jump:"))
        self.text_next_clone_jump.setText(_translate("pane_char_view", "Unknown"))
        self.label_17.setText(_translate("pane_char_view", "Remaining Jump Fatigue:"))
        self.text_jump_fatigue_remaining.setText(_translate("pane_char_view", "Unknown"))
        self.pushButton.setText(_translate("pane_char_view", "API Force Pull"))
        self.text_api_nextupdate_countdown.setText(_translate("pane_char_view", "05:34"))
        self.label_24.setText(_translate("pane_char_view", "Known Skills:"))
        self.text_known_skills.setText(_translate("pane_char_view", "Unknown"))
        self.label_23.setText(_translate("pane_char_view", "Skills at Level V:"))
        self.text_skills_at_level5.setText(_translate("pane_char_view", "Unknown"))
        self.label_22.setText(_translate("pane_char_view", "Total SP:"))
        self.text_total_sp.setText(_translate("pane_char_view", "Unknown"))
        self.label_25.setText(_translate("pane_char_view", "Free SP:"))
        self.text_freeSP.setText(_translate("pane_char_view", "Unknown"))
