# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_overview_char.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_overview_button(object):
    def setupUi(self, widget_overview_button):
        widget_overview_button.setObjectName("widget_overview_button")
        widget_overview_button.resize(352, 165)
        widget_overview_button.setMinimumSize(QtCore.QSize(352, 165))
        widget_overview_button.setMaximumSize(QtCore.QSize(352, 165))
        self.gridLayout = QtWidgets.QGridLayout(widget_overview_button)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pilot_image = QtWidgets.QLabel(widget_overview_button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pilot_image.sizePolicy().hasHeightForWidth())
        self.pilot_image.setSizePolicy(sizePolicy)
        self.pilot_image.setMinimumSize(QtCore.QSize(96, 96))
        self.pilot_image.setMaximumSize(QtCore.QSize(96, 96))
        self.pilot_image.setText("")
        self.pilot_image.setPixmap(QtGui.QPixmap("media/static/icons/blank_char.jpg"))
        self.pilot_image.setScaledContents(True)
        self.pilot_image.setObjectName("pilot_image")
        self.verticalLayout_3.addWidget(self.pilot_image)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.text_account_status = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_account_status.setFont(font)
        self.text_account_status.setStyleSheet("color: rgb(9, 127, 9);")
        self.text_account_status.setAlignment(QtCore.Qt.AlignCenter)
        self.text_account_status.setObjectName("text_account_status")
        self.verticalLayout_3.addWidget(self.text_account_status)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_name = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.text_name.setFont(font)
        self.text_name.setObjectName("text_name")
        self.verticalLayout_2.addWidget(self.text_name)
        self.text_isk = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.text_isk.setFont(font)
        self.text_isk.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_isk.setObjectName("text_isk")
        self.verticalLayout_2.addWidget(self.text_isk)
        self.text_sp = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.text_sp.setFont(font)
        self.text_sp.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_sp.setObjectName("text_sp")
        self.verticalLayout_2.addWidget(self.text_sp)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_currentSkill_timeRemains = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.text_currentSkill_timeRemains.setFont(font)
        self.text_currentSkill_timeRemains.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_currentSkill_timeRemains.setObjectName("text_currentSkill_timeRemains")
        self.verticalLayout.addWidget(self.text_currentSkill_timeRemains)
        self.text_current_skill = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_current_skill.setFont(font)
        self.text_current_skill.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_current_skill.setObjectName("text_current_skill")
        self.verticalLayout.addWidget(self.text_current_skill)
        self.text_skill_end_datetime = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_skill_end_datetime.setFont(font)
        self.text_skill_end_datetime.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_skill_end_datetime.setObjectName("text_skill_end_datetime")
        self.verticalLayout.addWidget(self.text_skill_end_datetime)
        self.text_queue_ends_in = QtWidgets.QLabel(widget_overview_button)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_queue_ends_in.setFont(font)
        self.text_queue_ends_in.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_queue_ends_in.setObjectName("text_queue_ends_in")
        self.verticalLayout.addWidget(self.text_queue_ends_in)
        self.text_jump_fatigue = QtWidgets.QLabel(widget_overview_button)
        self.text_jump_fatigue.setMinimumSize(QtCore.QSize(191, 0))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.text_jump_fatigue.setFont(font)
        self.text_jump_fatigue.setStyleSheet("color: rgb(91, 91, 91);")
        self.text_jump_fatigue.setObjectName("text_jump_fatigue")
        self.verticalLayout.addWidget(self.text_jump_fatigue)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)

        self.retranslateUi(widget_overview_button)
        QtCore.QMetaObject.connectSlotsByName(widget_overview_button)

    def retranslateUi(self, widget_overview_button):
        _translate = QtCore.QCoreApplication.translate
        widget_overview_button.setWindowTitle(_translate("widget_overview_button", "Form"))
        self.text_account_status.setText(_translate("widget_overview_button", "Omega"))
        self.text_name.setText(_translate("widget_overview_button", "pilot_name"))
        self.text_isk.setText(_translate("widget_overview_button", "0.00 ISK"))
        self.text_sp.setText(_translate("widget_overview_button", "0 SP"))
        self.text_currentSkill_timeRemains.setText(_translate("widget_overview_button", "0d, 0h, 0m, 0s"))
        self.text_current_skill.setText(_translate("widget_overview_button", "Skill_book level# (#sp/hr)"))
        self.text_skill_end_datetime.setText(_translate("widget_overview_button", "Mon 1/01/2018 00:00:00 PM"))
        self.text_queue_ends_in.setText(_translate("widget_overview_button", "Queue ends in 00d 00h 00m 00s"))
        self.text_jump_fatigue.setText(_translate("widget_overview_button", "Jump fatigue remaining: 00:00:00"))
